server:
  port: 8080

spring:
  aop:
    #优先使用JDK代理
    proxy-target-class: false
  datasource:
    username: root
    password: 320683buobao
    #url中database为对应的数据库名称
    url: jdbc:mysql://localhost:3306/database?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    #配置druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
      filter:
        commons-log:
          connection-logger-name: stat,wall,log4j
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
  freemarker:
    suffix: .ftl
    enabled: true
    charset: UTF-8
    content-type: text/html
    #暴露session对象的属性
    expose-session-attributes: true
    #模板加载地址
    template-loader-path: classpath:/templates/

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.turman.learning.entity
  configuration:
    lazy-loading-enabled: true
    lazy-load-trigger-methods: clone

#showSql
logging:
  level:
    com.turman.learning.mapper: debug

#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count-countSql